from collections import Counter
import json
from pathlib import Path

import networkx as nx
import pandas as pd

SCRIPT_DIR = Path(__file__).resolve().parent
OUTPUT_JSON = SCRIPT_DIR.parent / "viz_data" / "dataset.json"

NODE_SCALING = 2
# GraphML file generated by Gephi
INPUT_GRAPHML = "../graphml/epstein_photo_people_layout.graphml"

CATEGORY_COLORS = {
    "Inner Circle": '#8c3bff',
    "Academia & Science": '#018700',
    "Politics & Government":'#00acc6',
    "Entertainment & Media": '#e6a500',
    "Royalty & Aristocracy": '#ff7ed1',
    "Finance & Business": '#6b004f',
    "Fashion & Modeling":'#573b00',
    "Miscellaneous": '#005659',
    "Alleged Victim": '#15e18c',
    "Employee": '#0000dd',
    "Unknown": '#999999',
}

if __name__ == "__main__":
    G = nx.read_graphml(path=INPUT_GRAPHML)

    _nodes_df = pd.DataFrame.from_dict(
        dict(G.nodes(data=True)), orient="index"
    ).reset_index(drop=True)
    _edges_df = nx.to_pandas_edgelist(G=G)

    _nodes_df["degree"] = (_nodes_df["degree_root_2"] ** 2).astype(int)

    nodes_df = _nodes_df[["x", "y", "label", "size", "degree", "category", "total"]].copy()
    edges_df = _edges_df[["source", "target", "weight"]].copy()

    label_to_index = {
        t[0]: i
        for i, t in enumerate(
            Counter(list(edges_df["source"]) + list(edges_df["target"])).most_common()
        )
    }

    nodes_df["key"] = nodes_df["label"].map(label_to_index)
    nodes_df["size"] /= NODE_SCALING

    nodes_df["category"] = nodes_df["category"].fillna("Unknown")


    nodes = nodes_df.to_dict(orient="records")

    edges = [
        [label_to_index[e["source"]], label_to_index[e["target"]], e["weight"]]
        for e in edges_df.to_dict(orient="records")
    ]

    clusters = [k for k, _ in Counter(nodes_df["category"]).most_common()]

    data = {
        "nodes": nodes,
        "edges": edges,
        "clusters": [
            {"key": c, "color":CATEGORY_COLORS[c]}
            for c in clusters
        ],
    }

    OUTPUT_JSON.parent.mkdir(parents=True, exist_ok=True)
    with open(OUTPUT_JSON, "w") as f:
        json.dump(obj=data, fp=f, separators=(",", ":"))
