"""Generate ``site/partials/head-*.html`` from ``site/site_metadata.json``.

Single source of truth for the per-page ``<head>`` (title, description, canonical
URL, og:image, etc.) and the boilerplate shared across every page (site origin,
og:site_name, twitter card type, ...).

This is invoked as the first step of ``site/build.sh`` so the partials are always
in sync with the JSON. The generated files are committed so contributors can
build the site without running Python.

Edit ``site/site_metadata.json``, then re-run this script (or ``site/build.sh``).
"""

from __future__ import annotations

import html as html_lib
import json
from pathlib import Path

EPSTEIN_WEB_ROOT = Path(__file__).resolve().parent.parent
SITE_METADATA_PATH = EPSTEIN_WEB_ROOT / "site" / "site_metadata.json"
PARTIALS_DIR = EPSTEIN_WEB_ROOT / "site" / "partials"

GENERATED_BANNER = (
    "<!-- GENERATED by scripts/render_head_partials.py from site/site_metadata.json. "
    "Do not edit by hand; edits will be overwritten on the next build. -->"
)


def _esc(value: object) -> str:
    """Escape for use inside a double-quoted HTML attribute.

    Differs from ``html.escape(..., quote=True)``, which also escapes ``'``
    (valid but unnecessary inside double-quoted attributes; we keep ``'`` as-is
    so descriptions like "what's in it" stay readable in the generated HTML).
    """
    return html_lib.escape(str(value), quote=False).replace('"', "&quot;")


def render_head(page: dict, shared: dict) -> str:
    site_origin = shared["site_origin"].rstrip("/")
    cdn_base = shared["spaces_cdn_base"].rstrip("/")
    canonical_url = site_origin + page["url_path"]
    og_image_url = f"{cdn_base}/og/{page['og_image_filename']}"

    title = _esc(page["title"])
    desc = _esc(page["description"])
    canonical = _esc(canonical_url)
    og_image = _esc(og_image_url)
    og_image_alt = _esc(page["og_image_alt"])
    site_name = _esc(shared["og_site_name"])
    locale = _esc(shared["og_locale"])
    img_type = _esc(shared["og_image_type"])
    img_width = _esc(shared["og_image_width"])
    img_height = _esc(shared["og_image_height"])
    twitter_card = _esc(shared["twitter_card"])
    body_class = _esc(page["body_class"])

    return f"""{GENERATED_BANNER}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, viewport-fit=cover">
  <title>{title}</title>
  <meta name="description" content="{desc}" />
  <link rel="canonical" href="{canonical}" />
  <meta property="og:title" content="{title}" />
  <meta property="og:description" content="{desc}" />
  <meta property="og:url" content="{canonical}" />
  <meta property="og:site_name" content="{site_name}" />
  <meta property="og:locale" content="{locale}" />
  <meta property="og:type" content="website" />
  <meta property="og:image" content="{og_image}" />
  <meta property="og:image:secure_url" content="{og_image}" />
  <meta property="og:image:type" content="{img_type}" />
  <meta property="og:image:width" content="{img_width}" />
  <meta property="og:image:height" content="{img_height}" />
  <meta property="og:image:alt" content="{og_image_alt}" />
  <meta name="twitter:card" content="{twitter_card}" />
  <meta name="twitter:title" content="{title}" />
  <meta name="twitter:description" content="{desc}" />
  <meta name="twitter:image" content="{og_image}" />
  <link rel="icon" type="image/svg+xml" href="/favicon.svg">
  <link rel="stylesheet" href="/styles.css">
  <script src="/js/nav.js" defer></script>
  <script src="/js/disclaimer.js" defer></script>
</head>
<body class="{body_class}">
"""


def main() -> None:
    metadata = json.loads(SITE_METADATA_PATH.read_text(encoding="utf8"))
    shared = metadata["shared"]
    pages = metadata["pages"]
    seen_outs: set[str] = set()
    for page in pages:
        out_name = page["out"]
        if out_name in seen_outs:
            raise ValueError(f"Duplicate ``out`` entry in pages list: {out_name!r}")
        seen_outs.add(out_name)
        out_path = PARTIALS_DIR / out_name
        out_path.write_text(render_head(page, shared), encoding="utf8")
        print(f"wrote {out_path.relative_to(EPSTEIN_WEB_ROOT)}")


if __name__ == "__main__":
    main()
